
export default [
    {
        name: "HALP",
        description: "Ticket management system using a noSQL database to store login and ticket information",
        gitlink: "https://github.com/ikemous/halp", 
        weblink: "https://me-halp.herokuapp.com", 
        src: "./Images/halp.PNG ",
        languages: ["React", "Redux", "Typescript", "MongoDB", "CSS", "Node"],
    },
    {
        name: "Aninder",
        description: "Find your new furry friend using this web application. It uses multiple API calls and stores user data using a noSQL database",
        gitlink: "https://github.com/ikemous/React-Cat-Or-Dog", 
        weblink: "https://aninder.herokuapp.com", 
        src: "./Images/aninder.PNG",
        languages: ["React", "Typescript", "Redux", "Node", "CSS", "MongoDB", "API"],
    },
    {
        name: "Tic-Tac-Toe",
        description: "Unbeatable Tic-Tac-Toe application made using Visual Studio. Try going first or second, you won't beat this one!",
        gitlink: "https://github.com/ikemous/TicTacToe",
        src: "./Images/tictactoe.PNG",
        languages: ["C#", "WPF"],
    },
    {
        name: "My Pygame",
        description: "Game application created in python! Be a water animal who is getting invaded by multiple land creatures!",
        gitlink: "https://github.com/ikemous/learningPython",
        src: "./Images/pygame.PNG",
        languages: ["Python"],
    },
    {
        name: "Weather Dashboard",
        description: "Web application used to find the weather at the searched location. Featuring weather API usage and local storage",
        gitlink: "https://github.com/ikemous/weather", 
        weblink: "https://ikemous.github.io/weather/", 
        src: "./Images/weatherDashboard.PNG",
        languages: ["Javascript", "CSS", "HTML", "API"],
    },
    {
        name: "Movie Lover",
        description: "Web application with the purpose of searching and saving movies using the OMDB API. This application uses the MySQL Database",
        gitlink: "https://github.com/Robbie2497/Project-2", 
        weblink: "https://projectdash.herokuapp.com", 
        src: "./Images/movieLover.PNG",
        languages: ["Javascript", "API", "Node", "Handlebars", "CSS", "HTML"],
    },
    {
        name: "Burger Chomper",
        description: "Web application used with CRUD operations to track your burgers using a MySQL as the databse",
        gitlink: "https://github.com/ikemous/burger_logger", 
        weblink: "https://buger-eater.herokuapp.com", 
        src: "./Images/burgerChomper.PNG",
        languages: ["Javascript", "Node", "Handlebars", "MySQL", "CSS", "HTML"],
    },
];